mysql:
  host: mysql
  port: 3306
  user: root
  password: 55555
  db: boil
  collation: utf8_general_ci

server:
  addr: 0.0.0.0:9090
  mode: debug

jwt:
  secret: dsadsadsadsa
  tokentime: 100

redis:
  addr: redis:6379
  db: 0
  username:
  password:
