mysql:
  host: localhost
  port: 3306
  user: root
  password: 55555
  db: boil
  collation: utf8_general_ci

server:
  addr: localhost:8000
  mode: debug

jwt:
  secret: dsadsadsadsa
  tokentime: 100

redis:
  addr: localhost:6379
  db: 0
  username:
  password: 55555