version: "3.9"
services:
  boil:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mysql
    restart: on-failure
    volumes:
    - /root/docker-program/boil-gin/config.yaml:/config.yaml
  redis:
    image: "redis:6.2.2"
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "55555"
    volumes:
      - /root/docker-program/mysql-8.0/conf.d:/etc/mysql/conf.d
      - /root/docker-program/mysql-8.0/mysql-data:/var/lib/mysql